name: pythons
on:
  workflow_dispatch:

jobs:
  robot:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10
    steps:
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      - shell: bash
        run: python --version
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.8'
      - shell: bash
        run: python --version
      - shell: bash
        run: which python
      - name: Use 3.8
        shell: bash
        run: /opt/hostedtoolcache/Python/3.8.14/x64/bin/python -m pip install pipenv
      - name: Use 3.10
        shell: bash
        run: /opt/hostedtoolcache/Python/3.10.7/x64/bin/python -m pip install pipenv
