name: pythons
on:
  workflow_dispatch:

jobs:
  robot:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10
    steps:
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      - shell: bash
        run: python --version
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.8'
      - shell: bash
        run: python --version
      - shell: bash
        run: which python