name: robot-server
on:
  workflow_dispatch:

jobs:
  robot:
    env:
      PIPENV_VENV_IN_PROJECT: 1
    timeout-minutes: 10
    runs-on: "windows-2022"
    steps:
      - uses: 'actions/checkout@v3'
        with:
          repository: "Opentrons/opentrons"
          ref: edge
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.7"
          cache: 'pipenv'
          cache-dependency-path: |
            api/Pipfile.lock
            robot-server/Pipfile.lock
            shared-data/Pipfile.lock
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '14'
      - uses: './.github/actions/python/setup'
        with:
          project: 'robot-server'
      - name: Setup OT-2
        run: make -C robot-server setup-ot2
      - name: Run
        run: make -C robot-server dev & # works don't have to use: START "" thecommand
      - name: "sleep"
        if: ${{ always() }}
        run: |
          sleep 10s
      - name: "curl"
        if: ${{ always() }}
        run: |
          Invoke-WebRequest -Method 'Get' -Uri http://localhost:31950/modules -Headers @{'Accept' = 'application/json'; 'opentrons-version' = '*'}
      - name: "sleep"
        if: ${{ always() }}
        run: |
          sleep 20s
      - name: "curl"
        if: ${{ always() }}
        run: |
          cInvoke-WebRequest -Method 'Get' -Uri http://localhost:31950/modules -Headers @{'Accept' = 'application/json'; 'opentrons-version' = '*'}
