name: Workflow A

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    paths:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

jobs:
  print-group:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        shell: bash
        run: |
          echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}'
          echo "Awake"
      - name: Sleep for 4m
        shell: bash
        run: sleep 4m
