name: Workflow A

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        shell: bash
        run: |
          echo '${{ github.workflow }}-${{ github.sha }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}'
          echo "Awake"
      - name: Sleep for 4m
        shell: bash
        run: sleep 4m
